openapi: "3.0.2"
info:
  title: BeamMP-Server
  version: "1.0"
  description: |
    The BeamMP-Server optionally runs an HTTP server
    which can be used to query information about the server's 
    status, health, players, etc.
servers:
  - url: http://localhost:{port}/v1
    description: local BeamMP-Server
    variables:
      port:
        default: "8000"
paths:
  /players:
    get:
      summary: list of players on this server
      responses:
        "200":
          description: OK
          content:
            "application/json":
              schema:
                type: array
                example:
                  - "LionKor"
                  - "Titch"
                items:
                  type: string
  /config:
    get:
      summary: describes server configuration
      description: |
        An overview over the configuration currently
        used by this server.
      responses:
        "200":
          description: OK
          content:
            "application/json":
              schema:
                type: object
                properties:
                  name:
                    type: string
                    example: "my awesome beammp server"
                  description:
                    type: string
                    example: "join!"
                  max_players:
                    type: integer
                    example: 7
                  max_cars:
                    type: integer
                    example: 2
                  map:
                    type: string
                    example: "/levels/gridmap_v2/info.json"
                  private:
                    type: boolean
  /ready:
    get:
      summary: whether the server has started fully
      description: |
        True once all subsystems have started up.
        This doesn't tell you whether they're healthy, 
        check /health for that information.
      responses:
        "200":
          description: OK
          content:
            "text/plain":
              schema:
                type: boolean

  /health:
    get:
      summary: health of the server's systems
      responses:
        "200":
          description: OK
          content:
            "application/json":
              schema:
                type: object
                properties:
                  healthy:
                    type: boolean
                  good:
                    type: array
                    items:
                      type: string
                      example: "Heartbeat"
                  bad:
                    type: array
                    items:
                      type: string
                      example: "ResourceManager"
